delete: 
    - "app-detection-rule/unguard"
    - "application/unguard"
    - "management-zone/unguard"
    - "dashboard/Application Security Issues"
    - "synthetic-monitor/unguard.http"
    - "synthetic-monitor/unguard.clickpath"
    - "request-attributes/X-Client-Ip"
    ## infrastructure related configurations will not be deleted, thus commented out below 
    #- "auto-tag/app"
    #- "auto-tag/environment"
    #- "conditional-naming-processgroup/ACE Box - containername.namespace"
    #- "conditional-naming-processgroup/Java Springboot Naming"
    #- "conditional-naming-processgroup/MongoDB Naming"
    #- "conditional-naming-processgroup/NodeJS Naming"
    #- "conditional-naming-processgroup/Postgres Naming"
    #- "conditional-naming-processgroup/ {ProcessGroup:ExeName} {ProcessGroup:KubernetesBasePodName}"
    #- "conditional-naming-service/app.environment"
    #- "kubernetes-credentials/ACE-BOX"
    #- "synthetic-location/ACE-BOX"