---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-nginx-web
  labels:
    app: {{ .Release.Name }}-nginx-web
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-nginx-web
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-nginx-web
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
          - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: nginx-config
          configMap:
            name: {{ .Release.Name }}-ingress-config