---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
  name: {{ .Release.Name }}-easytravel-web
spec:
  rules:
  - host: {{ .Values.ingress.domain }}
    http:
      paths:
      - backend:
          service:
            name: {{ .Release.Name }}-nginx-custom-web
            port:
              name: nginx
        path: /
        pathType: ImplementationSpecific